#!/usr/bin/env bash
# Runs zensical with the Reference section enabled when the library is
# present under lib/ (see install-kit.sh and link-local-kit.sh), and with the
# plain zensical.toml otherwise. Arguments are passed through:
#
#   scripts/zensical.sh serve
#   scripts/zensical.sh build --clean
set -euo pipefail

cd "$(dirname "$0")/.."

kit="lib/cs_survival_kit"

# Only build and serve read the config; pass anything else straight through.
if [[ "${1:-}" != "build" && "${1:-}" != "serve" ]]; then
  exec zensical "$@"
fi

if [[ ! -e "$kit" ]]; then
  echo "note: $kit not found; building without the Reference section." >&2
  exec zensical "$@"
fi

# Label the Reference section with what is actually installed.
if [[ -L "$kit" ]]; then
  label="local"
else
  label="unknown"
  for dist_info in lib/cs_survival_kit-*.dist-info; do
    if [[ -d "$dist_info" ]]; then
      label="${dist_info#lib/cs_survival_kit-}"
      label="${label%.dist-info}"
    fi
  done
fi

{
  echo "# Generated by scripts/zensical.sh from zensical.toml and"
  echo "# zensical.reference.toml — do not edit."
  cat zensical.toml
  echo
  sed "s/@KIT_VERSION@/$label/" zensical.reference.toml
} > zensical.generated.toml

exec zensical "$@" --config-file zensical.generated.toml
